server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bregandert/config.git
          search-paths: blob/main
          clone-on-start: true
  application:
    name: config_server

logging:
  level:
    org.springframework.cloud: DEBUG

#    https://github.com/bolshakov-coach/springcloud-config/tree/master/springleveltwo

